### ISSUE TITLE
Bug on v 2.4.0

### ISSUE THREAD

**Issue by rafwell** [cossou/JasperPHP#81] opened 2017-11-24 19:27 UTC
Hello, after upgrade for 2.4.0 my script stop work. He is saying `Unable to load driver: com.mysql.jdbc.Driver`, i've downgraded to 2.3.0 and now work fine.

**Comment by cossou** [comment] 2017-11-26 23:56
Thanks, I will look into it to see if I find any problem.

Em 24/11/2017 7:27 da tarde, "Rafael Souza" <notifications@github.com>
escreveu:

**Comment by cossou** [comment] 2017-12-07 11:57
Hi @rafwell 

The problem is fixed in the new 2.5.0 version. 
The JDBC drivers were deleted from the JasperStarter/jdbc directory.

Thanks

**Closed by cossou** 2017-12-07 11:57 UTC
